### PR TITLE
changed default table styles

### PR DESCRIPTION
**Pull request by Adrianltd**
This PR will solve:
https://github.com/openstax/webview/issues/2154
https://github.com/openstax/webview/issues/2183
https://github.com/openstax/webview/issues/2184

It will also affect any other content that is created in tables eg `tables with equations`. 
https://katalyst01.cnx.org/contents/mwjClAV_@8.2:SXjiAlpU@8.2/Key-Equations

@openstaxalina This should look good also for tables with merged cells, paddings in cells also look good. It will be verified by QA.
I was thinking if we should make the `table head` border darker or thicker so it can be distinguished from the table body?

### CODE REVIEW

**Comment by lwtchu** [comment]
Can someone provide a screenshot of what it looks like now so I can give feedback?

Ideally - yes the header should have a thicker or darker line. 

Screen Shot 2019-05-28 at 3 07 14 PM
Currently there's a 1px(?) line for the header. The body table borders can be 0.5px if that makes it easier.

**Comment by helenemccarron** [comment]
@wilkus27 I know this wasn't your PR but would you like to take over?

**Comment by wilkus27** [comment]
@helenemccarron of course.
So I checked locally how it looks: 

image

For comparison this is how this table looks currently on katalyst01: (https://katalyst01.cnx.org/contents/kg0cimBs@14.1:Wqg4xZyG@7/6-3-Calculate-Activity-Based-Product-Costs)

image

Do we want to do any changes?

**Comment by openstaxalina** [comment]
Thank you @wilkus27!  We will provide feedback today.

**Comment by lwtchu** [comment]
@wilkus27 looks BEAUtiFUL. can you reduce the padding on the inside by half?
Screen Shot 2019-05-31 at 9 30 40 AM

**Comment by wilkus27** [comment]
@lwtchu Do you mean only in header or in every cell?

Here padding is reduced in every cell and from each side (left/right top/bottom):

image

Here, in every cell but only from top and bottom, left and right padding is the same as previously:

image

What looks better?

**Comment by wilkus27** [comment]
@lwtchu @openstaxalina What do you think about tables in examples, where background is grey?

With all of those changes it looks like that:
image

Currently on katalyst01: (https://katalyst01.cnx.org/contents/yqV9q0HH@18.1:SlIIi4zi@21/1-3-Subtract-Whole-Numbers)

image

**Comment by openstaxalina** [comment]
@wilkus27 thank you!  Larissa is out this week, so I will respond:

Please implement the second option for padding reduction, in which you reduced padding in every cell, but only top/bottom.

For the tables inside notes, please implement it as shown in your first screenshot ("With all of those changes it looks like that:").  

Thank you again!

**Pull request merged**
