### PR TITLE
Template Treasure Map

### PR DESCRIPTION
**Pull request by philschatz**
_(Not sure if this is code that should be included or if only the screenshots are useful)_

These screenshots describe which templates are used in order to generate the various parts of a page. It is useful for making changes and gets you a little closer to the JS code that is used to generate that particular part of the page.

TODO: Discuss if the screenshots should just be included in the repo under a `docs/` directory

# Home page:

image

image

# /contents

image

## Without the top nav bar:

image

## Bottom Downloads Tab
image

## Bottom History Tab

image

## Bottom Attribution Tab

image

## Bottom More Information Tab

image

# /browse

image

# /search

image

# /about

image

# /donate

image

# /workspace

image

### CODE REVIEW

**Comment by edwoodward** [comment]
@philschatz This is useful documentation, but should not be on production. Please add the screenshots to the documentation and we can close this PR.

**Comment by philschatz** [comment]
@edwoodward The code would not exist on production. It requires the dev to run `./script/add-template-comments` which edits the template files. I updated `docs/README.md` to clarify how to regenerate the screenshots.

**Comment by philschatz** [comment]
going to try re-opening the PR to retrigger the Jenkins build

**Comment by philschatz** [comment]
It seems like the Jenkins failure is not caused by this PR... so every commit regardless of the branch will fail (since nvm or something isn't installed on Jenkins)

**Comment by brittweinstein** [comment]
@philschatz can this be closed?

**Pull request closed without merging**
