### PR TITLE
removed dots from unordered lists in the preface

### PR DESCRIPTION
**Pull request by Adrianltd**
https://github.com/openstax/webview/issues/2198

### CODE REVIEW

**Comment by Adrianltd** [comment]
@openstaxalina I have removed those dots in webview, but @wilkus27 just noticed me that previously this was removed from the content https://github.com/openstax/content-managers/issues/500
Should my PR be removed and content managers will remove those dots?

**Comment by openstaxalina** [comment]
@Adrianltd thank you for pointing this out.  the reason we decided to remove the dots via the content in other titles is because @helenemccarron notified us (see comments on 
openstax/content-managers#500) that the change would impact all lists in recipes.  

What content is impacted by this PR?

**Comment by Adrianltd** [comment]
@openstaxalina only unordered lists inside the `Preface`, so it affects dotted lists only in the `Preface`.

**Comment by openstaxalina** [comment]
@Adrianltd great, thank you for letting me know.  This is an acceptable change.  Thanks again!

**Pull request merged**
